### ISSUE TITLE
Broke by ElvUI 13.18

### ISSUE THREAD

**Issue by Nifelhein** [cr4ckp0t/ElvUI_EquipmentSetsDT#5]
ElvUI 13.18 and following versions broke this, probabbly because of this on change log: Datatexts added through LibDataBroker will now start with LDB.

Error: the datatext still can be selected, but it is invisble, hovering over it still gives tooltip, left clicking still opens the character sheet and right clicing still gives the selection menu.

No LUA error generated, may be connected to an issue tracked on elvui's github: https://github.com/tukui-org/ElvUI/issues/767#issue-1537637488

**Comment by St0rmwhisper** [comment]
Fixed on version 4.1.9
